### PR TITLE
add support for esm

### PR DESCRIPTION
**Pull request by AllAwesome497**
https://app.asana.com/0/0/1202131546027041/f

We want to keep things simple for our users; instead of choosing `esm` or `cjs` we choose both.

This makes it so you can use import files in cjs and `require` in esm.   It additionally adds optional support for source maps.  By default, it wraps `Error.prepareStackTrace` in a way that should be transparent to anything done in userspace to modify Error.prepareStackTrace. (this is to avoid breaking stack traces if the user ends up requiring something like `source-map-support`).

Since I didn't feel like making an ast parser + printer in nodejs I opted to use swc (as esbuild doesn't have an api for parsing to ast + printing). 

`node_modules` is vendor-ed here since I didn't want to add complexity to the build process; happy to change this.

While this will add some additional latency to imports, it should be small enough that most users won't notice it.

I also added some tests for this, run by a go test.   These test the various behaviors which I fought with while making this.

### CODE REVIEW

**Comment by dan-stowell** [comment]
@airportyh prybar falls squarely in your court!

**Comment by sergeichestakov** [comment]
Gonna unboop this since no one is reviewing. @airportyh pls take a look or re-assign to someone else who might be a better fit

**Comment by airportyh** [comment]
Crossposting from https://replit.slack.com/archives/C030RJ2PRC7/p1659130866691439?thread_ts=1659115750.278649&cid=C030RJ2PRC7:

Wade and I had a discussion about a problem with trying to reconcile esm with cjs. I'll present here.

I have a repl with the prybar-nodejs enhanced with Wade's pr: https://replit.com/@tobyho/BuoyantPersonalSpyware
and a repl without, but using the older cjs compatible version of node-fetch: https://replit.com/@tobyho/PotableFloralwhiteBloatware.

 In the enhanced version, const fetch = require('node-fetch') works but calling it will get TypeError: fetch is not a function because the esm module inter-op will return an object with a bunch of properties on it, not a function. The user will probably try const { fetch } = require('node-fetch') but that will fail too. The correct fix is const fetch = require('node-fetch').default to the the "default export" of the module. I think if the user has find that, we've gone away from the beginner-friendly experience we are after.

We considered having require return the default value directly, but that would disallow users from importing exported properties other than the default value. We thought about copying those other exported properties to the object that is the default value, but what if that default value was an object that had specific values on it, then we would mutate the object, potentially changing the behavior of the code.

We considered have require return a proxy (wade already had a prototype: https://replit.com/@AllAwesome497/esm-require) which is callable and would dynamically fetch properties from either the default value object or the module object, but the problem there is what if there's a name conflict - the same property being present on the default value and the module object? There's no right answer, which is why compat layers return the default value in a "default" property.

**Comment by AllAwesome497** [comment]
Sounds like we won't be doing this.

**Pull request closed without merging**
