### PR TITLE
Ctrl-C improvements for python.

### PR DESCRIPTION
**Pull request by basicer**
- Add default ctrl+c handler to python3 + python3
- Fix Eval in python3

### CODE REVIEW

**Comment by basicer** [comment]
Yea, I'm not happy about it :(.  I all the C hackory I tried crashed.

**Comment by turbio** [comment]
what else did you try?
handling the signal in prybar and calling `signal.default_int_handler` doesn't work?

**Comment by basicer** [comment]
I tried calling the reasonable things in https://github.com/python/cpython/blob/27e2d1f21975dfb8c0ddcb192fa0f45a51b7977e/Modules/signalmodule.c but they mostly crashed :(

**Comment by basicer** [comment]
Fixes #4

**Pull request merged**
