### PR TITLE
Update nixpkgs

### PR DESCRIPTION
**Pull request by cbrewster**
Nixpkgs is out of date, the newest one does not have Python 3.8 so I added it back manually via overriding the attrs of python 3.9.

```
$ nix run .#prybar-python3
Python 3.8.18 (default, Aug 24 2023, 19:48:18)
[GCC 13.3.0] on linux
```

### CODE REVIEW

**Comment by cbrewster** [comment]
Current dependencies on/for this PR:

* master:
  * **PR #122** 👈

This comment was autogenerated by Freephite.

**Review by ryantm — APPROVED** [review]
Fine with me, but @airportyh should really take a look since he knows this part best.

**Comment by airportyh** [comment]
Is this to unblock updating the nixpkgs in goval? There's risk of breaking old repls because packages installed for 3.8 won't be recognized by 3.9. I can see some old class assignments/lessons breaking if they used any package. We've kind of deprecated prybar for [11 months](https://ask.replit.com/t/removing-prybar-from-the-run-button/65578). Perhaps we just let support know and have them help re-install the packages if needed. They'd need to change the `pyproject.toml` file to match the new version of Python, and then run `poetry install`.

**Review by airportyh — APPROVED** [review]

**Comment by cbrewster** [comment]
> Is this to unblock updating the nixpkgs in goval? There's risk of breaking old repls because packages installed for 3.8 won't be recognized by 3.9. I can see some old class assignments/lessons breaking if they used any package. We've kind of deprecated prybar for [11 months](https://ask.replit.com/t/removing-prybar-from-the-run-button/65578). Perhaps we just let support know and have them help re-install the packages if needed. They'd need to change the `pyproject.toml` file to match the new version of Python, and then run `poetry install`.

Yeah, the other option is pinning nixpkgs again to keep an older version or adding back a derivation for Python 3.8

**Comment by airportyh** [comment]
I can do a test to see how easy it is to adding back a derivation for Python 3.8.

**Pull request merged**
