### PR TITLE
Add Clojure support

### PR DESCRIPTION
**Pull request by finalfantasia**
This is so that Prybar can work with the official Clojure CLI tools which will replace Leiningen for REPLs and evaluating expressions/source files.

### CODE REVIEW

**Comment by finalfantasia** [comment]
Here is the PR for replacing Leiningen with the official Clojure CLI tools in the Docker image: https://github.com/replit/polygott/pull/28

**Comment by finalfantasia** [comment]
@kochman Sure, let me work on that, it's going to be more fun. 🙂

**Comment by finalfantasia** [comment]
@kochman With all the latest commits, `prybar-clojure` now supports custom `PS1`.

I had to dig a little bit into the "internals" of the Clojure source code to figure out how to make it work since the official `clojure` command doesn't provide any CLI option for customizing `PS1` (and/or `PS2`.) I got lucky with `PS1` as there's a "hook" that we can use to provide a function to print `PS1`.

As for `PS2`, things don't seem to be that straightforward and I may have to talk to one of the Clojure core team members to get their support. Depending on their priorities, it may take a while (if it ever happens) to get it working. Right now, I'm not so sure whether custom `PS2` support is a blocker (as I noticed that the Ruby REPL doesn't seem to support it either) and therefore we should spend time on it so please advise.

With all that said though, I think we can say that the combination of `prybar-clojure`/polygott has reached feature parity with the current Leiningen-based solution, making it a viable replacement at this point.

Please let me know your thoughts. 🙂

**Comment by finalfantasia** [comment]
After spending some time analyzing the Clojure source code, I came to the conclusion that it’s impossible to add `PS2` customization to prybar-clojure without making changes to the Clojure reader (which is one of the core components of Clojure.) It’s highly unlikely that the Clojure core team would accept such intrusive changes (for good reasons, of course.) therefore I gave up on going any further with this idea. I hope lack of `PS2` customization wouldn’t be a showstopper for adding Clojure support to prybar.

**Comment by amasad** [comment]
@finalfantasia thanks so much for this. We deployed but turned out to be very slow for the resources we give our containers. Especially since every run is a new instance of the interpreter. 

Our existing interpreter, which doesn't use prybar, starts a server in the background and uses the lein repl protocol. Any chance this can be done here?

**Comment by finalfantasia** [comment]
Hi @amasad ,

My apologies for the late response (I got caught up in other priorities in life) 😅

Yes, I noticed the long response time when I was trying out the new, Prybar/Polygott-backed Clojure REPL. I guess this (starting a new JVM process every time a user hits the Run button) is going to be an issue for any REPL that requires the JVM as well (Java and Scala come to mind)?

Anyway, it would be easier for me to answer your question and estimate the effort if I knew how a REPL.it REPL works end-to-end. Without knowing this, it just feels like a shot in the dark. It would be even better if I could set up a completely locally-running REPL.it REPL to play around with the various components in order to understand how they are connected together. I found some documentation about this on http://protodoc.turbio.repl.co/ but I'm not sure if that's what I'm after.

**Comment by turbio** [comment]
hey @finalfantasia, don't yet have a version of replit you can run yourself but I can offer a quick description of how the repl process works.

When you open up a new repl we'll start a fresh REPL process with `clojure-prybar -q -i`. When a user hits the run button we'll kill (SIGKILL) any existing REPL process and start a new process with `clojure-prybar -q -i <main file>`. If at any point the user hits stop we'll also kill any existing process and start `clojure-prybar -q -i`.

**Comment by finalfantasia** [comment]
Thank you, @turbio , that explains a lot!

Yeah, the Java Virtual Machine is notorious for its (relatively) slow start-up. This is a major reason, in the Clojure community, we go to great lengths to avoid restarting a REPL server (a JVM process) as much as possible when practicing REPL-aided development. [1][2]

The current behavior, as you described above, when a user hits the Run button is certainly not ideal in terms of performance and responsiveness when the user is working with a Clojure REPL. Is it possible to change it so that when the Run button is hit, instead of killing an existing REPL server and starting a new one, we simply reload the `main` namespace (i.e., `main.clj`) in an already existing REPL server?

[1] http://thinkrelevance.com/blog/2013/06/04/clojure-workflow-reloaded
[2] https://github.com/clojure/tools.namespace

**Pull request merged**
